apiVersion: v1
kind: Service
metadata:
  name: autocare360-chatbot-service
  namespace: autocare360
spec:
  selector:
    app: autocare360-chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP