piVersion: v1
kind: Service
metadata:
  name: autocare360-frontend-service
  namespace: autocare360
spec:
  selector:
    app: autocare360-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP