apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - chatbot-deployment.yaml
  - chatbot-service.yaml
  - db-redis-deployment.yaml
  - db-redis-service.yaml
  - db-mysql-deployment.yaml
  - db-mysql-service.yaml
  - storage/mysql-pvc.yaml
  - storage/redis-pvc.yaml
  # - network/ingress.yaml  # Commented out - use port-forward instead
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
